services:
  db:
    image: mysql:8.0
    container_name: solarapp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solar
    ports:
      - "3306:3306" 
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solarapp-backend
    environment:
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data: